version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    command: sh -c "npx prisma migrate deploy && npm run dev:debug"
    environment:
      PORT: 8000
      JWT_SECRET_KEY: 99eb92b3b4e6905ed5c03332314cfa629d51d2939f08769e9bd2f86028aa092b
      DATABASE_URL: postgresql://postgres:mypassword@host.docker.internal:5433/linx-db?schema=public
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: linx-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
